Examples/Backend/DataAdapters/DataAdapter-Picturepark/Assets/Common/PictureparkContentConverter.cs
> Remove not necessary code (done in PSCPR anyways)
> N/A
=> Remove not necessary code (done in PSCPR anyways)

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add created and modified dates to ProductDataObject
> https://trello.com/c/FJxCWIz3/1434-connect-thron-asset-da-to-thron-product-da-include-related-assets
=> Add created and modified dates to ProductDataObject

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add related products to asset data object
> https://trello.com/c/FJxCWIz3/1434-connect-thron-asset-da-to-thron-product-da-include-related-assets
=> Add related products to asset data object

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj, Examples/Frontend/ui-example-hello-world-1/package-lock.json, Examples/Frontend/ui-example-hello-world-1/package.json
> Unify products and asset data objects, and simplify resource asset handling
> https://trello.com/c/lRzwxPAL/1431-support-productdataobject-for-il
=> Unify products and asset data objects, and simplify resource asset handling

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj, Examples/Frontend/ui-example-hello-world-1/package-lock.json, Examples/Frontend/ui-example-hello-world-1/package.json
> Add additional fields to AssetDataObject, optimize product interface naming
> N/A
=> Add additional fields to AssetDataObject, optimize product interface naming

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Introduce ETag for Integration Layer thumbnails
> https://trello.com/c/vSI2oluQ/1428-etag-for-il-thumbnails
=> Introduce ETag for Integration Layer thumbnails

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj, Examples/Frontend/ui-example-hello-world-1/package.json
> Add asset relationship types
> N/A
=> Add asset relationship types

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow to steer visibility of categories like for menu items
> N/A
=> Allow to steer visibility of categories like for menu items

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow to use GIFs / animated GIFs for resource images
> https://app.frontapp.com/open/cnv_18eyxqdy?key=6dJExRBDasloYk1yu4UkuIiMxuV6XryQ
=> Allow to use GIFs / animated GIFs for resource images

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow to manage on-hover background images for menu item
> https://app.frontapp.com/open/cnv_18eyxqdy?key=6dJExRBDasloYk1yu4UkuIiMxuV6XryQ
=> Allow to manage on-hover background images for menu item

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow default values for localized string models
> https://trello.com/c/Vx2cCue5/1462-migrate-resource-based-texts-to-embedded-texts-where-it-makes-sense
=> Allow default values for localized string models

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Fix ValueForJson Equals method
> N/A
=> Fix ValueForJson Equals method

Examples/Frontend/ui-example-hello-world-1/package-lock.json, Examples/Frontend/ui-example-hello-world-1/package.json
> Migrate to new text handling
> https://trello.com/c/Vx2cCue5/1462-migrate-resource-based-texts-to-embedded-texts-where-it-makes-sense
=> Migrate to new text handling

Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj
> Update Picturepark SDK
> N/A
=> Update Picturepark SDK

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Upgrade RestSharp from 110.2.0 to 112.0.0 
> https://trello.com/c/hxsrOBtU/1471-upgrade-restsharp-from-11020-to-11200
=> Upgrade RestSharp from 110.2.0 to 112.0.0 

Examples/Backend/Connectors/Connector-Picturepark/PictureparkConnectorStartup.cs, Examples/Backend/Connectors/Connector-SharePoint/SharepointConnectorStartup.cs
> Adjust image URLs to use CDN
> N/A
=> Adjust image URLs to use CDN

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/Assets/AllowedValues/OutputFormatAllowedValuesProvider.cs, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow to use proxy original formats as input for custom downloads
> https://app.frontapp.com/open/cnv_19dld61i?key=igZxxvnXuWW2w-IztwVC16fLIagth4_N
=> Allow to use proxy original formats as input for custom downloads

Examples/Backend/Connectors/Connector-SharePoint/AllowedValues/SharepointFolderIdProvider.cs, Examples/Backend/Connectors/Connector-SharePoint/Client/ISharepointClient.cs, Examples/Backend/Connectors/Connector-SharePoint/Client/Impl/SharepointClient.cs
> Optimize search for SharePoint folders
> https://app.frontapp.com/open/cnv_19iqvpxy?key=x8CVF2iPSKFX9N0D-dp3aNS3WqFlb97S
=> Optimize search for SharePoint folders

Examples/Backend/Connectors/Connector-SharePoint/OneDriveConnectorConfiguration.cs, Examples/Backend/Connectors/Connector-SharePoint/SharepointConnectorConfiguration.cs, Examples/Backend/Connectors/Connector-SharePoint/SharepointOneDriveConnectorConfiguration.cs
> Correctly order SharePoint configuration
> N/A
=> Correctly order SharePoint configuration

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Ingestion mode for Integration Layer and Box
> https://trello.com/c/yGHnWXnm/1493-authentic-brands-high-volume-ingestion-for-integration-layer
=> Ingestion mode for Integration Layer and Box

Examples/Backend/Connectors/Connector-SharePoint/Client/Impl/SharepointDefaultRequestFailedHandler.cs
> Fix error code handling for SharePoint
> N/A
=> Fix error code handling for SharePoint

Examples/Backend/Connectors/Connector-SharePoint/Client/Impl/SharepointDefaultRequestFailedHandler.cs
> Handle error when querying some SharePoint assets
> N/A
=> Handle error when querying some SharePoint assets

Examples/Backend/Connectors/Connector-SharePoint/Client/Impl/SharepointDefaultRequestFailedHandler.cs
> Handle additional SharePoint error code
> N/A
=> Handle additional SharePoint error code

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add metadata properties to file metadata data object
> https://trello.com/c/yGHnWXnm/1493-authentic-brands-high-volume-ingestion-for-integration-layer
=> Add metadata properties to file metadata data object

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add flag to HttpClientExtensions allowing us to allow JSON responses
> N/A
=> Add flag to HttpClientExtensions allowing us to allow JSON responses

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add AlternateIds to AssetDataObject
> https://trello.com/c/7px4lDxc/1477-tenovos-webhooks
=> Add AlternateIds to AssetDataObject

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add AI content to metadata model
> https://trello.com/c/yGHnWXnm/1493-authentic-brands-high-volume-ingestion-for-integration-layer
=> Add AI content to metadata model

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow to configure permissions for share settings
> https://app.frontapp.com/open/cnv_19stw9li?key=edAuryk23eXBu4PY7-Ne-QKHlqtjuqYe
=> Allow to configure permissions for share settings

Examples/Frontend/ui-example-hello-world-1/package-lock.json, Examples/Frontend/ui-example-hello-world-1/package.json
> Fix racing condition in the metadata formatter
> N/A
=> Fix racing condition in metadata formatter

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add external links to asset data objects
> Add ignore option to download and permission requests
> https://app.frontapp.com/open/cnv_ysvns9i?key=9HNVmOcL5xTIZBVrbmYjPV5kptyvLaGi
=> Add external links to asset data objects, add ignore option to download and permission requests

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow collections to be shared with user groups and users from the backend
> https://trello.com/c/xrVcNesi/1453-assign-user-groups-to-collections
=> Allow collections to be shared with user groups and users from the backend

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Introduce Cloudinary Upload Widget and generic dialog page implementation
> https://trello.com/c/ck54FEv5/1518-cloudinary-external-uploader
=> Introduce Cloudinary Upload Widget and generic dialog page implementation

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Update integration layer help text
> N/A
=> Update integration layer help text

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/Search/SharepointAssetsSearch.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/SharepointAssetsDataAdapter.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/SharepointAssetsDataAdapterConfiguration.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Support folder navigation
> https://trello.com/c/Yy1TGeQc/1524-support-folder-navigation
=> Support folder navigation

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj, Examples/Frontend/ui-example-hello-world-1/package-lock.json, Examples/Frontend/ui-example-hello-world-1/package.json
> Fix form constants
> https://trello.com/c/Yy1TGeQc/1524-support-folder-navigation
=> Fix form constants

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Support custom forms for task handlers
> https://app.frontapp.com/open/msg_2b794gnq?key=uS725bX7jn6oA5R1UZ1JAqwHuwjqYoP-
=> Support custom forms for task handlers

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Rename simple form download request download button
> https://app.frontapp.com/open/msg_2b794gnq?key=uS725bX7jn6oA5R1UZ1JAqwHuwjqYoP-
=> Rename simple form download request download button

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add folder path data structure
> https://trello.com/c/6LEQ1XuE/1529-add-folder-path-to-root-folder-into-folder-and-asset-data-objects
=> Add folder path data structure

Examples/Backend/Connectors/Connector-SharePoint/Client/ISharepointClient.cs, Examples/Backend/Connectors/Connector-SharePoint/Client/Impl/SharepointClient.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/IntegrationLayer/SharepointAssetsIntegrationLayer.cs
> Set IgnoreTopLevelFolders to false when root folder is selected and true for sub folders
> N/A
- [N/A]  Pull request is linked to task tracker where applicable
=> Set IgnoreTopLevelFolders to false when root folder is selected and true for sub folders

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Client/ISharepointClient.cs, Examples/Backend/Connectors/Connector-SharePoint/Client/Impl/SharepointClient.cs, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/IntegrationLayer/SharepointAssetsIntegrationLayer.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow to upload files to Smint.io Portals
> https://trello.com/c/XA5RVm4H/1531-fifa-file-upload-facility
=> Allow to upload files to Smint.io Portals

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Fix file format text for upload data source
> https://trello.com/c/XA5RVm4H/1531-fifa-file-upload-facility
=> Fix file format text for upload data source

Examples/Backend/Connectors/Connector-SharePoint/AllowedValues/SharepointFolderIdProvider.cs, Examples/Backend/Connectors/Connector-SharePoint/Client/ISharepointClient.cs, Examples/Backend/Connectors/Connector-SharePoint/Client/Impl/SharepointClient.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/Common/SharepointContentConverter.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/IntegrationLayer/SharepointAssetsIntegrationLayer.cs
> Description here
> Reference related issues here
=> Set ParentFolderPaths to assetDataObject and folderDataObject

Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-Picturepark/PictureparkConnector.cs, Examples/Backend/DataAdapters/DataAdapter-Picturepark/Assets/Common/PictureparkContentConverter.cs, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj
> Update Picturepark SDK version
> N/A
=> Update Picturepark SDK version

Examples/Backend/DataAdapters/DataAdapter-Picturepark/Assets/Common/PictureparkContentConverter.cs, Examples/Backend/DataAdapters/DataAdapter-Picturepark/Assets/Read/PictureparkAssetsRead.cs
> Better solution for sha1hash for Picturepark
> N/A
=> Better solution for sha1hash for Picturepark

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/Assets/PictureparkAssetsDataAdapterConfiguration.cs, Examples/Backend/DataAdapters/DataAdapter-Picturepark/Assets/Read/PictureparkAssetsRead.cs, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/SharepointAssetsDataAdapterConfiguration.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Support file-type based hi-res categorizations
> https://app.frontapp.com/open/cnv_19y39c5y?key=ifyOqfFLXVhm5D0HHfLQNKkMgSzDfbVV
=> Support file-type based hi-res categorizations

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add additional relationship types
> N/A
=> Add additional relationship types

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj, Examples/Frontend/ui-example-hello-world-1/package-lock.json, Examples/Frontend/ui-example-hello-world-1/package.json
> Allow to define width for metadata attributes
> https://trello.com/c/gntxzExx/1536-add-form-based-metadata-viewer
=> Allow to define width for metadata attributes

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj, Examples/Frontend/ui-example-hello-world-1/package-lock.json, Examples/Frontend/ui-example-hello-world-1/package.json
> Add date time format options
> https://trello.com/c/gntxzExx/1536-add-form-based-metadata-viewer
=> Add date time format options

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow to choose data object arrays in metadata chooser
> https://trello.com/c/gntxzExx/1536-add-form-based-metadata-viewer
=> Allow to choose data object arrays in metadata chooser

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj, Examples/Frontend/ui-example-hello-world-1/package-lock.json, Examples/Frontend/ui-example-hello-world-1/package.json
> Improve metadata parsing, update dependencies
> https://trello.com/c/gntxzExx/1536-add-form-based-metadata-viewer
=> Improve metadata parsing, update dependencies

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add AssetCaptions to RelatedAssetsDataObject
> https://trello.com/c/RmNE7RLT/1532-build-poc-for-richemont
=> Add AssetCaptions to RelatedAssetsDataObject

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add related assets caption object
> https://trello.com/c/RmNE7RLT/1532-build-poc-for-richemont
=> Add related assets caption object

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add JSON path selector for asset captions
> https://trello.com/c/RmNE7RLT/1532-build-poc-for-richemont
=> Add JSON path selector for asset captions

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Fix localized strings construction
> N/A
=> Fix localized strings construction

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add disabled flag for menu item and category
> https://app.frontapp.com/open/cnv_1a3i4vti?key=q85LYXOtVLLMqeeUBZw-eOLGk7ObKwar
=> Add disabled flag for menu item and category

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow chunked file uploads
> https://app.frontapp.com/open/cnv_1a1bz046?key=WLGDyRcMwwL67JV4F6DgXshB0J78wKG6
=> Allow chunked file uploads

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow uploader to report progress
> https://app.frontapp.com/open/cnv_1a1bz046?key=WLGDyRcMwwL67JV4F6DgXshB0J78wKG6
=> Allow uploader to report progress

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Fix empty strings in LocalizedStringsModel
> N/A
=> Fix empty strings in LocalizedStringsModel

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-Picturepark/Metamodel/PictureparkMetamodelBuilder.cs, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Allow to define relationships using the adjust metadata data processor
> https://app.frontapp.com/open/cnv_1a9t9x1y?key=omMRNq0FGQHHZ3lJ75sd8aoZkkaVMs-K
=> Allow to define relationships using the adjust metadata data processor

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add generic request task handler and form
> https://app.frontapp.com/open/cnv_1a6j5el2?key=5xgK6CLeRmQYBCY3pXIu6_7JFC8gAwHU
=> Add generic request task handler and form

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj
> Add image for transparent header to menu item
> https://app.frontapp.com/open/cnv_1alr0h7a?key=N7SRxNlbRA2DSUMIQVn1ZAnOHa0-QOdJ
=> Add image for transparent header to menu item

Examples/Backend/Connectors/Connector-HelloWorld/Connector-HelloWorld.csproj, Examples/Backend/Connectors/Connector-Picturepark/Connector-Picturepark.csproj, Examples/Backend/Connectors/Connector-SharePoint/Connector-SharePoint.csproj, Examples/Backend/DataAdapters/DataAdapter-HelloWorld/DataAdapter-HelloWorld.csproj, Examples/Backend/DataAdapters/DataAdapter-Picturepark/DataAdapter-Picturepark.csproj, Examples/Backend/DataAdapters/DataAdapter-SharePoint/DataAdapter-SharePoint.csproj, Examples/Backend/DataAdapters/Portals-HelloWorld-TestDriver/Portals-Connector-SDK-TestDriver.HelloWorld.Test.csproj, Examples/Backend/DataAdapters/Portals-Picturepark-TestDriver/Portals-Connector-SDK-TestDriver.Picturepark.Test.csproj, Examples/Backend/DataAdapters/Portals-Sharepoint-TestDriver/Portals-Connector-SDK-TestDriver.Sharepoint.Test.csproj, Examples/Frontend/ui-example-hello-world-1/package-lock.json, Examples/Frontend/ui-example-hello-world-1/package.json
> Introduce watermark feature for the Cloudinary connector
> https://app.frontapp.com/open/cnv_1ajsp28m?key=SMxt7rpU7GPKuLAQepQwJgzND-M_0I4S
=> Introduce watermark feature for the Cloudinary connector

Examples/Backend/DataAdapters/DataAdapter-Picturepark/Assets/Read/PictureparkAssetsRead.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/Read/SharepointAssetsRead.cs
> Description here
> Reference related issues here
=> Remove IgnoreMissingAssets

Examples/Backend/DataAdapters/DataAdapter-Picturepark/Assets/Read/PictureparkAssetsRead.cs
> Description here
> Reference related issues here
=> Ignore missing assets during GetAssetsDownloadItemMappingsAsync

Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/Search/SharepointAssetsSearch.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/SharepointAssetsDataAdapter.cs, Examples/Backend/DataAdapters/DataAdapter-SharePoint/Assets/SharepointAssetsDataAdapterConfiguration.cs
> Description here
> Reference related issues here
=> Add new AI DA configuration properties
